[project]
name = "baba-is-agi"
version = "0.1.0"
description = "Agentic programs for playing Baba Is You"
authors = ["femtomc"]
channels = ["conda-forge"]
platforms = ["osx-arm64", "linux-64", "win-64"]

[tasks]
# Install core package
install = "pip install -e ."

# Quick entry points
play = "python -m baba.play"
agent-random = "python agents/random_agent.py"
agent-demo = "python agents/demo_agent.py"


[dependencies]
python = ">=3.12"
pip = "*"

[environments]
default = []
